version: "latest"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pwd
      POSTGRES_DB: app_db
    ports:
      - 5432:5432
    command: postgres -N 1000
